arcus-azure/arcus.scripting

- README.md
Closes #28 
Closes #27 
Closes #24
> Docs - update README with scripting info

- docs/index.md
Fix missing component name in docs
> Fix missing component name

- docs/preview/features/powershell/arm.md
- docs/preview/features/powershell/azure-api-management.md
- docs/preview/features/powershell/azure-data-factory.md
- docs/preview/features/powershell/azure-devops.md
- docs/preview/features/powershell/azure-key-vault.md
- docs/preview/features/powershell/azure-storage.md
> Docs - add table of contents per topic

- README.md
The PowerShell badge in the README was not sending the user to the PowerShell Gallery to the actual package.
> Fix - send PS badge to gallery

- README.md
Update README with a more correct installation message with the available common packages.
Relates to http://github.com/arcus-azure/arcus/issues/92
> Docs - update README with a more correct installlation message

- docs/features/powershell/arm.md
- docs/features/powershell/azure-api-management.md
- docs/features/powershell/azure-data-factory.md
- docs/features/powershell/azure-devops.md
- docs/features/powershell/azure-key-vault.md
- docs/features/powershell/azure-storage.md
- docs/v0.1.3/features/powershell/arm.md
- docs/v0.1.3/features/powershell/azure-api-management.md
- docs/v0.1.3/features/powershell/azure-data-factory.md
- docs/v0.1.3/features/powershell/azure-devops.md
- docs/v0.1.3/features/powershell/azure-key-vault.md
- docs/v0.1.3/features/powershell/azure-storage.md
- docs/v0.1.3/index.md
Publishes the feature docs of the recent v0.1.3 release.
Relates to #74 , #1
> Docs - publish v0.1.3 feature docs

- README.md
Updating the readme.md to contain full overview of the currently available modules + how to install them.
Closes #99
> Update installation overview

- docs/preview/features/powershell/azure-api-management.md
- src/Arcus.Scripting.ApiManagement/Arcus.Scripting.ApiManagement.psd1
- src/Arcus.Scripting.ApiManagement/Arcus.Scripting.ApiManagement.psm1
- src/Arcus.Scripting.ApiManagement/Arcus.Scripting.ApiManagement.pssproj
- src/Arcus.Scripting.ApiManagement/Scripts/Restore-AzApiManagementService.ps1
- src/Arcus.Scripting.Tests.Unit/Arcus.Scripting.ApiManagement.tests.ps1
Creates new PS module function in the API Management service PS module to restore an API Management service.
Closes #76
> Feature - restore API Management service

- src/Arcus.Scripting.Tests.Integration/Arcus.Scripting.LogicApps.tests.ps1
- src/Arcus.Scripting.Tests.Unit/Arcus.Scripting.ApiManagement.tests.ps1
- src/Arcus.Scripting.Tests.Unit/Arcus.Scripting.Security.tests.ps1
Adds some backdoor testing for test mocks (technically they were stubs, but with the backdoor testing they became mocks 😉).
Closes #107
> Testing - add backdoor testing for LogicApps integration tests

- src/Arcus.Scripting.All/Arcus.Scripting.All.psd1
The Arcus.Scripting.All PS module was missing the Arcus.Scripting.Sql PS module.
Closes #145
> fix: add SQL module in All module

- src/Arcus.Scripting.ApiManagement/Arcus.Scripting.ApiManagement.psm1
- src/Arcus.Scripting.ApiManagement/Scripts/Backup-AzApiManagementService.ps1
- src/Arcus.Scripting.ApiManagement/Scripts/Create-AzApiManagementApiOperation.ps1
- src/Arcus.Scripting.ApiManagement/Scripts/Import-AzApiManagementApiPolicy.ps1
- src/Arcus.Scripting.ApiManagement/Scripts/Import-AzApiManagementOperationPolicy.ps1
- src/Arcus.Scripting.ApiManagement/Scripts/Import-AzApiManagementProductPolicy.ps1
- src/Arcus.Scripting.ApiManagement/Scripts/Remove-AzApiManagementDefaults.ps1
- src/Arcus.Scripting.ApiManagement/Scripts/Restore-AzApiManagementService.ps1
- src/Arcus.Scripting.KeyVault/Arcus.Scripting.KeyVault.psm1
- src/Arcus.Scripting.KeyVault/Scripts/Get-AzKeyVaultAccessPolicies.ps1
- src/Arcus.Scripting.KeyVault/Scripts/Set-AzKeyVaultSecretFromFile.ps1
- src/Arcus.Scripting.LogicApps/Arcus.Scripting.LogicApps.psm1
- src/Arcus.Scripting.LogicApps/Scripts/Disable-AzLogicApp.ps1
- src/Arcus.Scripting.LogicApps/Scripts/Disable-AzLogicAppsFromConfig.ps1
- src/Arcus.Scripting.LogicApps/Scripts/Enable-AzLogicApp.ps1
- src/Arcus.Scripting.LogicApps/Scripts/Enable-AzLogicAppsFromConfig.ps1
- src/Arcus.Scripting.Security/Arcus.Scripting.Security.psm1
- src/Arcus.Scripting.Security/Scripts/Get-AzCachedAccessToken.ps1
- src/Arcus.Scripting.Security/Scripts/Remove-AzResourceGroupLocks.ps1
- src/Arcus.Scripting.Sql/Arcus.Scripting.Sql.psm1
- src/Arcus.Scripting.Sql/Scripts/Invoke-AzSqlDatabaseMigration.ps1
- src/Arcus.Scripting.Storage.Blob/Arcus.Scripting.Storage.Blob.psm1
- src/Arcus.Scripting.Storage.Blob/Scripts/Upload-AzFilesToBlobStorage.ps1
- src/Arcus.Scripting.Storage.FileShare/Arcus.Scripting.Storage.FileShare.psm1
- src/Arcus.Scripting.Storage.FileShare/Scripts/Copy-AzFileShareStorageFiles.ps1
- src/Arcus.Scripting.Storage.FileShare/Scripts/Create-AzFileShareStorageFolder.ps1
- src/Arcus.Scripting.Storage.Table/Arcus.Scripting.Storage.Table.psm1
- src/Arcus.Scripting.Storage.Table/Scripts/Create-AzTableStorageAccountTable.ps1
Use the same approach when describing parameters and verifying their values.
> chore: streamline parameter order and guards

- README.md
Let's use the general `Arcus.Scripting.All` PS package to show on which version we're at.
> docs: update README.md with general package

- build/templates/run-pester-tests.yml
- docs/preview/features/powershell/azure-storage-table.md
- src/Arcus.Scripting.Storage.Table/Arcus.Scripting.Storage.Table.psd1
- src/Arcus.Scripting.Storage.Table/Arcus.Scripting.Storage.Table.psm1
- src/Arcus.Scripting.Storage.Table/Scripts/Create-AzTableStorageAccountTable.ps1
- src/Arcus.Scripting.Tests.Integration/Arcus.Scripting.Storage.Table.tests.ps1
- src/Arcus.Scripting.Tests.Integration/Arcus.Scripting.Tests.Integration.pssproj
- src/Arcus.Scripting.Tests.Unit/Arcus.Scripting.Storage.Table.tests.ps1
Use real-life Azure resources for the integration tests of the Azure Table storage PS module.
Relates to #174
> test: use real az resources for table storage integration tests

- build/templates/run-pester-tests.yml
- src/Arcus.Scripting.DevOps/Scripts/Save-AzDevOpsBuild.ps1
- src/Arcus.Scripting.Tests.Integration/Arcus.Scripting.DevOps.tests.ps1
- src/Arcus.Scripting.Tests.Integration/Arcus.Scripting.Tests.Integration.pssproj
Adding integration test for the `Save-AzDevBuild`.
Closes #193
> test: add integration test for saving az devops build forever

- CONTRIBUTING.md
- README.md
Add contribution guide to the repo to explain and guide new contributers.
Closes #188
> docs: add contribution guide

- docs/preview/02-Features/powershell/azure-security.md
- src/Arcus.Scripting.Security/Scripts/Remove-AzResourceGroupLocks.ps1
- src/Arcus.Scripting.Tests.Integration/Arcus.Scripting.Security.tests.ps1
- src/Arcus.Scripting.Tests.Integration/Arcus.Scripting.Tests.Integration.pssproj
- src/Arcus.Scripting.Tests.Unit/Arcus.Scripting.Security.tests.ps1
Integration test the removal of Azure resource locks with actual Azure resources.
Relates to #174
> test: remove az resource locks

- docs/preview/02-Features/powershell/azure-security.md
- src/Arcus.Scripting.Security/Arcus.Scripting.Security.psm1
- src/Arcus.Scripting.Security/Scripts/Get-AzCachedAccessToken.ps1
- src/Arcus.Scripting.Tests.Integration/Arcus.Scripting.Security.tests.ps1
Updated script and documentation to fix Get-AzCachedAccessToken -AssignGlobalVariables
Closes #238
> fix: Get-AzCachedAccessToken -AssignGlobalVariables

- .github/CODEOWNERS
> chore: add @pim-simons to code-owners

- src/Arcus.Scripting.Tests.Integration/Arcus.Scripting.Sql.tests.ps1
Drops all SQL tables from our test SQL server on each test suite run.
Closes #261
> test: drop sql tables each test run

- docs/preview/02-Features/powershell/azure-integration-account.md
Added documentation to the script added in PR https://github.com/arcus-azure/arcus.scripting/pull/265
>  feat: Provide documentation to the script to upload agreements into an Integration Account

- src/Arcus.Scripting.ApiManagement/Scripts/Create-AzApiManagementApiOperation.ps1
- src/Arcus.Scripting.ApiManagement/Scripts/Import-AzApiManagementApiPolicy.ps1
- src/Arcus.Scripting.ApiManagement/Scripts/Import-AzApiManagementOperationPolicy.ps1
- src/Arcus.Scripting.ApiManagement/Scripts/Import-AzApiManagementProductPolicy.ps1
- src/Arcus.Scripting.ApiManagement/Scripts/Remove-AzApiManagementDefaults.ps1
- src/Arcus.Scripting.ApiManagement/Scripts/Set-AzApiManagementApiSubscriptionKey.ps1
- src/Arcus.Scripting.ApiManagement/Scripts/Upload-AzApiManagementCertificate.ps1
- src/Arcus.Scripting.Tests.Unit/Arcus.Scripting.ApiManagement.tests.ps1
Added context validation for Azure API Management. 
Closes https://github.com/arcus-azure/arcus.scripting/issues/220
> feat: Add APIM context validation

- docs/preview/03-Features/powershell/arm.md
- docs/preview/03-Features/powershell/azure-api-management.md
- docs/preview/03-Features/powershell/azure-app-service.md
- docs/preview/03-Features/powershell/azure-data-factory.md
- docs/preview/03-Features/powershell/azure-devops.md
- docs/preview/03-Features/powershell/azure-integration-account.md
- docs/preview/03-Features/powershell/azure-key-vault.md
- docs/preview/03-Features/powershell/azure-logic-apps.md
- docs/preview/03-Features/powershell/azure-management.md
- docs/preview/03-Features/powershell/azure-security.md
- docs/preview/03-Features/powershell/azure-sql.md
- docs/preview/03-Features/powershell/azure-storage/azure-storage-blob.md
- docs/preview/03-Features/powershell/azure-storage/azure-storage-fileshare.md
- docs/preview/03-Features/powershell/azure-storage/azure-storage-table.md
Removed table of contents as it is already handled by the sidebar.
Closes https://github.com/arcus-azure/arcus.scripting/issues/318
> docs: removed table of contents

- docs/preview/03-Features/powershell/azure-api-management.md
- docs/preview/03-Features/powershell/azure-app-service.md
- docs/preview/03-Features/powershell/azure-data-factory.md
- docs/preview/03-Features/powershell/azure-devops.md
- docs/preview/03-Features/powershell/azure-integration-account.md
- docs/preview/03-Features/powershell/azure-key-vault.md
- docs/preview/03-Features/powershell/azure-logic-apps.md
- docs/preview/03-Features/powershell/azure-security.md
- docs/preview/03-Features/powershell/azure-sql.md
- docs/preview/03-Features/powershell/azure-storage/azure-storage-blob.md
- docs/preview/03-Features/powershell/azure-storage/azure-storage-fileshare.md
- docs/preview/03-Features/powershell/azure-storage/azure-storage-table.md
Split PowerShell script samples into multiple lines for clarity.
Closes https://github.com/arcus-azure/arcus.scripting/issues/319
> docs: Split PowerShell script samples into multiple lines for clarity

- src/Arcus.Scripting.Tests.Integration/Arcus.Scripting.IntegrationAccount.tests.ps1
Woops, forgot to save the remaining assertions of the Azure Integration Account tests.
Follow-up of the #349 PR.
> chore: assert remaining trim day integration account

- docs/preview/03-Features/powershell/azure-management.md
- docs/preview/03-Features/powershell/azure-security.md
- docs/preview/03-Features/powershell/azure-sql.md
- docs/preview/03-Features/powershell/azure-storage/azure-storage-blob.md
- docs/preview/03-Features/powershell/azure-storage/azure-storage-fileshare.md
- docs/preview/03-Features/powershell/azure-storage/azure-storage-table.md
- src/Arcus.Scripting.ActiveDirectory/Scripts/Add-AzADAppRoleAssignment.ps1
- src/Arcus.Scripting.Management/Scripts/Get-AzApiManagementResourceManagementUrl.ps1
- src/Arcus.Scripting.Management/Scripts/Get-AzApiManagementSoftDeletedResources.ps1
- src/Arcus.Scripting.Management/Scripts/Remove-AzApiManagementSoftDeletedService.ps1
- src/Arcus.Scripting.Management/Scripts/Restore-AzApiManagementSoftDeletedService.ps1
- src/Arcus.Scripting.Security/Scripts/Get-AzCachedAccessToken.ps1
- src/Arcus.Scripting.Security/Scripts/New-AzResourceGroupRoleAssignment.ps1
- src/Arcus.Scripting.Sql/Scripts/Invoke-AzSqlDatabaseMigration.ps1
- src/Arcus.Scripting.Storage.Blob/Scripts/Upload-AzFilesToBlobStorage.ps1
- src/Arcus.Scripting.Storage.FileShare/Scripts/Create-AzFileShareStorageFolder.ps1
- src/Arcus.Scripting.Storage.FileShare/Scripts/Upload-AzFileShareStorageFiles.ps1
- src/Arcus.Scripting.Storage.Table/Scripts/Create-AzTableStorageAccountTable.ps1
- src/Arcus.Scripting.Tests.Integration/Arcus.Scripting.Management.tests.ps1
- src/Arcus.Scripting.Tests.Unit/Arcus.Scripting.Management.tests.ps1
Streamline logging and level across Powershell modules from `Arcus.Scripting.Management` to `Arcus.Scripting.Storage.Table`, alphabetically.
Relates to #155
> chore: streamline logging across modules 2

- netlify.toml
Add redirect to ARM templates.
Closes #358
> chore: add arm templates redirect

- CONTRIBUTING.md
Use `main` branch in contribution guide.
> chore: use main branch in contribution guide

- src/Arcus.Scripting.LogicApps/Scripts/Cancel-AzLogicAppRuns.ps1
- src/Arcus.Scripting.LogicApps/Scripts/Disable-AzLogicAppsFromConfig.ps1
- src/Arcus.Scripting.LogicApps/Scripts/Resubmit-FailedAzLogicAppRuns.ps1
Fixes https://github.com/arcus-azure/arcus.scripting/issues/390
> fix: Added the `-FollowNextPageLink` parameter to the `Get-AzLogicAppRunHistory` command

- build/psgallery-release.yml
wrong notation used, fixes the NuGetToolInstaller task
> fix: fix NuGetToolInstaller task

- src/Arcus.Scripting.Tests.Integration/Arcus.Scripting.IntegrationAccount.tests.ps1
Adds retries to integration account actions as these seem to fail regularly since last week, it seems like connection issues.
Closes https://github.com/arcus-azure/arcus.scripting/issues/405
> feat: add retries to integration account actions

- docs/package-lock.json
- docs/package.json
Due to merge conflicts on https://github.com/arcus-azure/arcus.scripting/pull/401 and https://github.com/arcus-azure/arcus.scripting/pull/403, this new PR to update the packages.
> chore: update packages

- src/Arcus.Scripting.Storage.Table/Scripts/Set-AzTableStorageEntities.ps1
Closes https://github.com/arcus-azure/arcus.scripting/issues/416
> fix: updated schema for `Test-Json` in Set-AzTableStorageEntities

- build/templates/run-pester-tests.yml
Add `Import-Module Microsoft.PowerShell.Management -Force` to fix the linux powershell update task in the pipeline.
> fix: Linux Powershell update

- build/templates/replace-tokens.yml
- build/templates/run-pester-tests.yml
Update the replace tokens task
> chore: Update replacetokens task

- build/psgallery-release.yml
`--Version` to `--RequiredVersion`
Closes https://github.com/arcus-azure/arcus.scripting/issues/442
> fix: `--Version` to `--RequiredVersion`

- docs/preview/03-Features/powershell/azure-sql.md
- docs/versioned_docs/version-v1.5.0/03-Features/powershell/azure-sql.md
Document the `DatabaseVersionTable` parameter.
Closes #454
> docs: Add missing documentation for Arcus.Scripting.Sql
