arcus-azure/arcus.scripting

src/Arcus.Scripting.ApiManagement/Arcus.Scripting.ApiManagement.psd1, src/Arcus.Scripting.DataFactory/Arcus.Scripting.DataFactory.psd1, src/Arcus.Scripting.KeyVault/Arcus.Scripting.KeyVault.psd1, src/Arcus.Scripting.Storage/Arcus.Scripting.Storage.psd1
=> Chore - add specific module versions for required modules

docs/preview/index.md
Both the ARM and the DevOps link in the index page was missing.
This PR add these.
=> Docs - update index page

docs/preview/index.md
The index was not referencing the Azure Table Storage feature docs page correctly.
This PR changes that.
=> Docs - update the index page to correctly reference Azure Table Storage

build/psgallery-release.yml
Azure DevOps release pipeline YAML still was using the Arcus template value for the GitHub repository.
=> Fix - use correct GitHub repository in PS Gallery release

src/Arcus.Scripting.DataFactory/Arcus.Scripting.DataFactory.psd1
Spaces are not allowed in the tags of a PowerShell manifest file; but the DataFactory still had these.
=> Fix - remove invalid spaces in DataFactory manifest

src/Arcus.Scripting.KeyVault/Arcus.Scripting.KeyVault.psd1, src/Arcus.Scripting.Storage.Table/Arcus.Scripting.Storage.Table.psd1
Spaces are not allowed in PowerShell manifests, so remove them in all.
=> Fix - remove spaces from PS manifests

docs/preview/features/powershell/azure-api-management.md, src/Arcus.Scripting.ApiManagement/Arcus.Scripting.ApiManagement.psd1, src/Arcus.Scripting.ApiManagement/Arcus.Scripting.ApiManagement.psm1, src/Arcus.Scripting.ApiManagement/Arcus.Scripting.ApiManagement.pssproj, src/Arcus.Scripting.ApiManagement/Scripts/Set-AzApiManagementApiSubscriptionKey.ps1, src/Arcus.Scripting.Tests.Unit/Arcus.Scripting.ApiManagement.tests.ps1
Provides script on API Management PS module that sets the subscription header and query parameter to an API running on API Management.
Closes #39
=> Feature - set subscription keys to an API in Azure API Management

docs/features/powershell/arm.md, docs/features/powershell/azure-api-management.md, docs/features/powershell/azure-data-factory.md, docs/features/powershell/azure-devops.md, docs/features/powershell/azure-key-vault.md, docs/features/powershell/azure-storage.md, docs/preview/features/powershell/arm.md, docs/preview/features/powershell/azure-api-management.md, docs/preview/features/powershell/azure-data-factory.md, docs/preview/features/powershell/azure-devops.md, docs/preview/features/powershell/azure-key-vault.md, docs/preview/features/powershell/azure-logic-apps.md, docs/preview/features/powershell/azure-storage.md, docs/v0.1.3/features/powershell/arm.md, docs/v0.1.3/features/powershell/azure-api-management.md, docs/v0.1.3/features/powershell/azure-data-factory.md, docs/v0.1.3/features/powershell/azure-devops.md, docs/v0.1.3/features/powershell/azure-key-vault.md, docs/v0.1.3/features/powershell/azure-storage.md
Signed-off-by: Tom Kerkhove <kerkhove.tom@gmail.com>
Use `Install-Module` instead of `Import-Module` because Import only works when you've installed it first
=> Use `Install-Module` instead of `Import-Module`

build/ci-build.yml
Validation of all the Arcus PowerShell modules during the CI build pipeline.
Closes #126
=> Chore - validate PowerShell module manifest during CI build

build/ci-build.yml
Publish PS modules with the low-level `nuget` CLI commands so we can skip the `RequiredModules` validation which is not correct in this context. An extra module manifest syntax validation is happening (#127).
Closes #128
=> Fix - push PS modules with `RequiredModules` to MyGet

docs/features/powershell/azure-security.md
Fixes the securitty docs where it uses the RoleAssignmentDefinition parameter in the New-AzResourceGroupRoleAssignment instead of the RoleDefinitionName.
Closes #144
=> fix: incorrect parameter in new role assignment security docs

src/Arcus.Scripting.KeyVault/Scripts/Get-AzKeyVaultAccessPolicies.ps1
When the Get-AzKeyVaultAccesspolicies is run against a non existing KV, make sure that the returned object contains a list property which is empty.
By doing so, the return type is consistent with what we get back when the KV does exist.
#166
=> feat: Return an object with an empty list property when KV does not exist

docs/v0.4.3/index.md
We should add the older versions to the v0.4.3 release so we have a more easy navigation between versions.
=> docs: add older versions for v0.4.3 release

build/ci-build.yml, build/psgallery-release.yml, build/variables/build.yml
Use `ubuntu-latest` for vm image of the build pipelines.
Relates to https://github.com/arcus-azure/arcus/issues/144
=> fix: use ubuntu-latest for build pipelines

build/templates/run-pester-tests.yml
Make sure that we can install preview PS modules when testing the Pester tests.
Otherwise, we can't release preview PS modules.
=> fix: add `-AllowPrerelease` to the Pester PS module installation

build/templates/run-pester-tests.yml
We should import preview modules as script files, so let's use that for all.
=> fix: import security PS module as file

build/ci-build.yml, build/psgallery-release.yml, build/templates/run-pester-tests.yml
We should consider using the security PS module of the gallery when building preview packages.
=> fix: insert prerelease information during release build

build/psgallery-release.yml, build/tools/psd1-to-nuspec.ps1
Trouble when building prereleases NuGet packages. Seems like there's a problem with the tool-script we're using.
Including exported DSC resources causing the problem, but since we're not using that, I commented out and documented.
=> fix: prerelease nuget generation

docs/preview/features/powershell/azure-devops.md
Added an example of how to use the Save-AzDevOpsBuild function in an Azure DevOps pipeline.
=> Improved usage documentation on Save-AzDevOpsBuild

netlify.toml
Added redirects for the broken API Management and Azure Storage documentation links.
Closes https://github.com/arcus-azure/arcus.scripting/issues/249 and https://github.com/arcus-azure/arcus.scripting/issues/250
=> fix: added redirects for broken links

src/Arcus.Scripting.DevOps/Scripts/Set-AzDevOpsArmOutputs.ps1, src/Arcus.Scripting.Tests.Integration/Arcus.Scripting.DevOps.tests.ps1, src/Arcus.Scripting.Tests.Integration/appsettings.json, src/Arcus.Scripting.Tests.Unit/Arcus.Scripting.DevOps.tests.ps1
When using YAML pipelines the Release.ReleaseName is empty, if this is the case use Build.DefinitionName and Build.BuildNumber and use this as the releasename in the variable group description.
Closes https://github.com/arcus-azure/arcus.scripting/issues/251
=> fix: make sure the variable group description uses a releasename when using YAML pipelines

docs/preview/02-Features/powershell/arm.md, docs/versioned_docs/version-v0.1.3/02-Features/powershell/arm.md, docs/versioned_docs/version-v0.2/02-Features/powershell/arm.md, docs/versioned_docs/version-v0.3/02-Features/powershell/arm.md, docs/versioned_docs/version-v0.4.3/02-Features/powershell/arm.md, docs/versioned_docs/version-v0.4/02-Features/powershell/arm.md, docs/versioned_docs/version-v0.5/02-Features/powershell/arm.md
Added documentation on the injection instructions into an ARM template and what they do.
Closes https://github.com/arcus-azure/arcus.scripting/issues/226
=> feat: Provide documentation on various modes for injecting content into an ARM template

src/Arcus.Scripting.KeyVault/Scripts/Get-AzKeyVaultAccessPolicies.ps1
Remove print command "Current access policies: $armAccessPoliciesParameter"
on script arcus.scripting\src\Arcus.Scripting.KeyVault\Scripts\Get-AzKeyVaultAccessPolicies.ps1
Closes https://github.com/arcus-azure/arcus.scripting/issues/262
=> feat: remove print "Current access policies: $armAccessPoliciesParameter"

src/Arcus.Scripting.Tests.Integration/Arcus.Scripting.IntegrationAccount.tests.ps1
Fixes the conflicted Azure Integration Account private certificate key name in the integration test.
Relates to #276
=> test: generate integration account certificate key name

src/Arcus.Scripting.LogicApps/Scripts/Disable-AzLogicAppsFromConfig.ps1
Typo fix `performing` in Azure Logic Apps script for disabling Logic Apps.
=> chore: typo 'performing` in disabling Azure LogicApps script

src/Arcus.Scripting.Tests.Integration/Arcus.Scripting.IntegrationAccount.tests.ps1
Since we are now using unique keynames we don't need to purge the keyvault keys anymore for the private keys in the private key tests. This was causing tests to sometimes fail as the purging happened to fast after initial deletion.
=> test: removal of purging keyvault key

docs/preview/02-Features/powershell/azure-devops.md
Added YAML examples for Set-AzDevOpsArmOutputsToPipelineVariables and Set-AzDevOpsArmOutputsToVariableGroup using Windows and Linux agents. Also documented required variable group permissions for Set-AzDevOpsArmOutputsToVariableGroup.
Closes #212
=> docs: updated Azure DevOps feature docs for setting ARM outputs

src/Arcus.Scripting.KeyVault/Scripts/Get-AzKeyVaultAccessPolicies.ps1, src/Arcus.Scripting.Tests.Unit/Arcus.Scripting.KeyVault.tests.ps1
Write-Host when all the policies are successfully retrieving from key vault and also added details in verbose for each policy. 
The following fields are printed in verbose logging: Tenant Id; Object Id;  Keys; Secrets; Certificates; Storage
Closes #271 
Note: The fields Keys, Secrets, Certificates and Storage only display information about the access permissions of the policy, not the sensitive data. 
E.g. keys : {Get, List, Set, Delete}
=> feat: Add logging to Get-AzKeyVaultAccessPolicies #271

docs/preview/02-Features/powershell/azure-devops.md
Updated the Azure DevOps docs on how to install the Arcus packages inside your pipeline.
Previously, using -Force, this step could take up to 5 minutes.
Now, by registering the repository and using -AllowClobber step takes one minute.
Relates to #284
=> docs: updated Azure DevOps feature docs regarding installing Arcus packages in pipelines

docs/preview/01-index.md, docs/versioned_docs/version-v0.6.0/01-index.md, docs/versioned_docs/version-v0.6.0/02-Features/powershell/arm.md, docs/versioned_docs/version-v0.6.0/02-Features/powershell/azure-devops.md, docs/versioned_docs/version-v0.6.0/02-Features/powershell/azure-management.md
Due to un-synced upstream from the 'master', there were some feature docs that weren't yet part of the v0.6 release.
=> fix: update with remaining v0.6 feature docs

docs/preview/02-Features/powershell/azure-app-service.md, docs/versioned_docs/version-v0.6.0/02-Features/powershell/azure-app-service.md
Should be 'App Service' probably, instead of 'Integration Account. Should be fixed now.
=> docs: use 'app service' io 'integration account' fix

docs/preview/02-Features/powershell/azure-app-service.md, docs/preview/02-Features/powershell/azure-management.md, docs/versioned_docs/version-v0.6.0/02-Features/powershell/azure-app-service.md, docs/versioned_docs/version-v0.6.0/02-Features/powershell/azure-management.md
Due to the fact that the layout code was not on the first line, we had some problems with formatting. Should be fixed now.
=> docs: fix az management title in feature docs

src/Arcus.Scripting.ApiManagement/Scripts/Import-AzApiManagementApiPolicy.ps1, src/Arcus.Scripting.ApiManagement/Scripts/Import-AzApiManagementOperationPolicy.ps1, src/Arcus.Scripting.ApiManagement/Scripts/Import-AzApiManagementProductPolicy.ps1
- Fixed the casing of `PolicyFilePath` parameter in the `Import-AzApiManagementApiPolicy` command.
- Added the `-PassThru` param to the `Set-AzApiManagementPolicy` to fix the `Import-AzApiManagementApiPolicy`, `Import-AzApiManagementOperationPolicy` and `Import-AzApiManagementProductPolicy` commands
Closes https://github.com/arcus-azure/arcus.scripting/issues/322
Closes https://github.com/arcus-azure/arcus.scripting/issues/323
=> fix: fixed casing of parameter and fixed return param of Set-AzApiManagementPolicy command

docs/preview/02-Guidelines/setting-arm-outputs-to-azure-devops-variable-group.md
Added a guide for setting arm outputs to azure devops variable group.
Closes https://github.com/arcus-azure/arcus.scripting/issues/314
=> docs: added guide for setting arm outputs to azure devops variable group

src/Arcus.Scripting.Tests.Integration/Arcus.Scripting.IntegrationAccount.tests.ps1
Since the integration tests were asserting on seconds, we would sometimes get failues in the like of `Expected collection @('2022-12-23T05:33:25', '2022-12-23T05:33:24') to contain '2022-12-23T05:26:03', but it was not found.` because there is a time delay somewhere that causes the expected creation time of Azure Integration account types to shift. Therefore, it would be better to assert the creation time trimmed on the day instead of on the second. Then, only when you work arround midnight and run the tests at an exact time, you would maybe run into this 😀.
=> test: assert trimmed day in integration account tests

README.md
Since we stopped support on the `Arcus.Scripting.All` package, we should use another on in the `README.md` as example.
=> chore: use arm package as default

docs/docusaurus.config.js
Use `main` branch in GitHub edit.
=> chore: use main branch in gh edit

src/Arcus.Scripting.Tests.Integration/Arcus.Scripting.IntegrationAccount.tests.ps1
Use random generated Azure Integration Account Partner files so that it does not conflict with other test runs that tries to create/delete the Partner with the same name.
Relates to #369
=> feat: use generative partner files for Azure Integration Account integration tests

build/psgallery-release.yml
Attempt to verify if none of the release PowerShell modules return a `BadRequest` without halting the release of the remaining modules.
Closes #368
=> chore: update w/ ps release verification

docs/preview/03-Features/powershell/azure-devops.md, src/Arcus.Scripting.DevOps/Arcus.Scripting.DevOps.psm1, src/Arcus.Scripting.DevOps/Scripts/Save-AzDevOpsBuild.ps1, src/Arcus.Scripting.Tests.Integration/Arcus.Scripting.DevOps.tests.ps1, src/Arcus.Scripting.Tests.Unit/Arcus.Scripting.DevOps.tests.ps1
Added an optional DaysToKeep parameter where you can specify how many days to pipeline run must be saved.
To do this I had to move to api version 7.0, so needed some more changes that I initially expected (also in the tests).
Closes https://github.com/arcus-azure/arcus.scripting/issues/382
=> feat: added optional DaysToKeep parameter to Save-AzDevOpsBuild

build/psgallery-release.yml
The release to the powershell gallery sometimes failes because of the version of the nuget tool. This PR makes sure we always use the latest version of the tool.
=> fix: use latest version of nuget during release

src/Arcus.Scripting.LogicApps/Scripts/Disable-AzLogicAppsFromConfig.ps1, src/Arcus.Scripting.Tests.Unit/Arcus.Scripting.LogicApps.tests.ps1
Get-AzLogicAppRunHistory is used multiple times when it only needs to be used once, optimisation
=> fix: Redundant use of Get-AzLogicAppRunHistory

build/psgallery-release.yml
Make sure the log.txt file exists so the logging from the nuget push command can be written there.
Related to https://github.com/arcus-azure/arcus.scripting/issues/388
=> fix: Make sure the log.txt file exists during release pipeline

build/psgallery-release.yml
Added some logging to figure out where the `No such file or directory` error is coming from. 
Related to https://github.com/arcus-azure/arcus.scripting/issues/388
=> fix: added logging to see which files we are processing during push to nuget

src/Arcus.Scripting.Tests.Integration/Arcus.Scripting.DevOps.tests.ps1, src/Arcus.Scripting.Tests.Integration/appsettings.json
Enable integration test for devops variable group description.
We use a different way to authenticate towards the DevOps API since the `$env:SYSTEM_ACCESSTOKEN` doesn't work for variable groups when triggered by GitHub.
Closes https://github.com/arcus-azure/arcus.scripting/issues/255
=> fix: enable integration test for devops variable group description

build/psgallery-release.yml
Removed the logging of the step to push to the powershell gallery to see if the logging causes the error. 
Related to https://github.com/arcus-azure/arcus.scripting/issues/388
=> fix: remove logging in push to powershell gallery

src/Arcus.Scripting.Tests.Integration/Connect-MgGraphFromConfig.ps1
Conditionally use securestring for `Connect-MgGraph` in integration tests.
=> fix: Conditionally use securestring for `Connect-MgGraph`

build/psgallery-release.yml
Fix setting the filename in the powershell gallery push
=> fix: Filename in powershell gallery push

docs/preview/03-Features/powershell/azure-api-management.md, docs/preview/03-Features/powershell/azure-storage/azure-storage-table.md, src/Arcus.Scripting.ApiManagement/Arcus.Scripting.ApiManagement.psm1, src/Arcus.Scripting.ApiManagement/Scripts/Backup-AzApiManagementService.ps1, src/Arcus.Scripting.Storage.Table/Arcus.Scripting.Storage.Table.psm1, src/Arcus.Scripting.Storage.Table/Scripts/Create-AzTableStorageAccountTable.ps1, src/Arcus.Scripting.Tests.Integration/Arcus.Scripting.Security.tests.ps1, src/Arcus.Scripting.Tests.Unit/Arcus.Scripting.ApiManagement.tests.ps1
Closes https://github.com/arcus-azure/arcus.scripting/issues/426
Also had to add a delay to `Create-AzTableStorageAccountTable.ps1` as this was failing the integration tests and documentation states that a remove action can take 40 seconds: https://learn.microsoft.com/en-us/rest/api/storageservices/Delete-Table?redirectedfrom=MSDN#remarks
> Note that deleting a table is likely to take at least 40 seconds to complete. If you attempt an operation against the table while it's being deleted, the service returns status code 409 (Conflict).
=> fix: `Backup-AzApiManagementService`: Use managed identity for connection between APIM and Storage Account

src/Arcus.Scripting.DevOps/Arcus.Scripting.DevOps.psm1, src/Arcus.Scripting.Tests.Unit/Arcus.Scripting.DevOps.tests.ps1
The heading whitespace is considered a part of the value when setting a variable in Azure DevOps. This PR removes that.
=> fix: az devops takes heading space as part of value

src/Arcus.Scripting.Sql/Arcus.Scripting.Sql.psm1, src/Arcus.Scripting.Sql/Scripts/Invoke-AzSqlDatabaseMigration.ps1
Introduced a new parameter `DatabaseVersionTable` which has a default value ('DatabaseVersion').
This parameter allows to specify the name of the table that must be used to keep track of applied DB migrations.
Closes #448
=> feat: Configurable database-version table-name

.github/workflows/bump-docs-version.yml, build/psgallery-release.yml, build/templates/trigger-bump-docs-version.yml
* Adds a GitHub workflow `bump-docs-version.yml` that runs the necessary steps described in the `/docs/README.md` to bump a new feature documentation version and proposes these changes in a PR.
* Adds a step in the Azure DevOps PowerShell Gallery release pipeline that triggers the workflow described above with the user-provided package version.
Together, they auto-trigger a new feature docs PR with the package version that is provided via Azure DevOps, making the release process more automated.
=> chore(docs): auto-trigger new feature docs version via release pipeline
